services:
  db:
    image: mariadb:10
    container_name: wp_db
    restart: unless-stopped
    environment:
      # Lendo as senhas do arquivo .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
  
  wordpress:
    depends_on:
      - db
    build: .
    image: wp-server-custom-image
    container_name: wp_app
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: wp_nginx
    restart: unless-stopped
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
      - proxy_network

networks:
  app-network:
    driver: bridge
  proxy_network:
    external: true

volumes:
  db_data:
